version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    container_name: card-game-postgres
    ports:
      - "5435:5432"
    volumes:
      - ./cardgame_init.sql:/docker-entrypoint-initdb.d/cardgame_init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: katana123
  node:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./
    links:
      - postgres
    ports:
      - "4000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: katana123
      POSTGRES_PORT: 5435
    container_name: card-game-backend
    volumes:
      - app:/usr/src/app
volumes:
  postgres-data:
  app:
